name: Build

on:
  push:
    branches: [ crac ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: bash ./configure
    - name: make
      run: make
