name: Build

on:
  push:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: antonkozlov/docker-build
    steps:
    - uses: actions/checkout@v2
    - run: | 
        id=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/org-crac/criu/releases/tags/HEAD | jq .assets[0].id)
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/org-crac/criu/releases/assets/$id -LJOH 'Accept: application/octet-stream'
        tar axf criu-dist.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}

    - run: bash ./configure --disable-warnings-as-errors --with-native-debug-symbols=none
    - run: |
        make images
        mv build/linux-x86_64-server-release/images/jdk .
    - run: |
        cp criu-dist/sbin/criu jdk/lib/criu
        sudo chown root:root jdk/lib/criu
        sudo chmod u+s jdk/lib/criu
      
    - run: tar -zcf jdk.tar.gz jdk
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: HEAD
        release_name: Release HEAD
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./jdk.tar.gz
        asset_name: jdk.tar.gz
        asset_content_type: application/gzip
