name: C/C++ CI

on:
  push:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: docker.pkg.github.com/org-crac/docker-build/image:latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: bash ./configure
    - name: make
      run: make
