name: C/C++ CI

on:
  push:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: bash ./configure
    - name: make
      run: make
