name: C/C++ CI

on:
  push:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: antonkozlov/docker-build
    steps:
    - uses: actions/checkout@v2
    - run: bash ./configure --disable-warnings-as-errors
    - run: make images
    - uses: actions/upload-artifact@v2
      with:
        name: jdk
        path: build/*/images/jdk
